'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Mainnamespace.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Թաքցնել.
        '''</summary>
        Friend ReadOnly Property CmdHide() As String
            Get
                Return ResourceManager.GetString("CmdHide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ցուցադրել.
        '''</summary>
        Friend ReadOnly Property CmdShow() As String
            Get
                Return ResourceManager.GetString("CmdShow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ուշադրություն.
        '''</summary>
        Friend ReadOnly Property MsgBoxCaption() As String
            Get
                Return ResourceManager.GetString("MsgBoxCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Սույն բաժինը դեռևս մշակման մեջ է.
        '''</summary>
        Friend ReadOnly Property MsgNotReady() As String
            Get
                Return ResourceManager.GetString("MsgNotReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Հիմնարկը գրանցված չէ:.
        '''</summary>
        Friend ReadOnly Property MsgNotRegistered() As String
            Get
                Return ResourceManager.GetString("MsgNotRegistered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Տվյալների բազան, որին դուք միացած եք, անհրաժեշտ է թարմացնել: Թարմացումը իրականացնելուց առաջ պարտադիր է տվյալների բազայի ախրիվացումը: Ցանկանում եք շարունակել՞:.
        '''</summary>
        Friend ReadOnly Property MsgRefreshAndArchieveBase() As String
            Get
                Return ResourceManager.GetString("MsgRefreshAndArchieveBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Տվյալների բազան, որին դուք միացած եք, անհրաժեշտ է թարմացնել.
        '''</summary>
        Friend ReadOnly Property MsgRefreshBase() As String
            Get
                Return ResourceManager.GetString("MsgRefreshBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ցանկանում  եք սկսել տվյալների բազայի վերականգնման գործընթացը՞:.
        '''</summary>
        Friend ReadOnly Property MsgRepairBase() As String
            Get
                Return ResourceManager.GetString("MsgRepairBase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Տվյալների բազայի վերականգնման գործընթացը ընդհատված է.
        '''</summary>
        Friend ReadOnly Property MsgRestoreInterrupted() As String
            Get
                Return ResourceManager.GetString("MsgRestoreInterrupted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Հնարավոր չէ կապ հաստատել SQL սերվերի հետ: Ցանկանում  եք փոխել սերվերի հետ կապի փոփոխականները?.
        '''</summary>
        Friend ReadOnly Property MsgSQLConnectionFailed() As String
            Get
                Return ResourceManager.GetString("MsgSQLConnectionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SQL սերվերի հետ կապը բացակայում է:.
        '''</summary>
        Friend ReadOnly Property MsgSQLNoConnection() As String
            Get
                Return ResourceManager.GetString("MsgSQLNoConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Տվյալների բազան, որին դուք միացած եք, ավելի նոր է քան ծրագրային փաթեթը: Աշխատանքը հնարավոր չէ շարունակել:.
        '''</summary>
        Friend ReadOnly Property MsgWorkFailed() As String
            Get
                Return ResourceManager.GetString("MsgWorkFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.
        '''</summary>
        Friend ReadOnly Property strSoftwareMajorVersion() As String
            Get
                Return ResourceManager.GetString("strSoftwareMajorVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3.0.0.2.
        '''</summary>
        Friend ReadOnly Property strSoftwareMinorVersion() As String
            Get
                Return ResourceManager.GetString("strSoftwareMinorVersion", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
